[theme]
primaryColor = "#4B3FE3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 50
maxMessageSize = 200

[browser]
gatherUsageStats = false
